---

- name: extract zip file
  ansible.builtin.unarchive:
    src:  ~/project/artifact.tar.gz
    dest: ~/
  
- name: installing dependencies
  shell: |
    cd ~
    npm install

- name: restarting pm2 server
  shell: |
    pm2 stop default
    pm2 start npm -- start
